# Study day 1

### Data load & setting

In [5]:
import pandas as pd

In [2]:
#붓꽃 품종 분류 데이터 load
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [8]:
#fearture 이름 확인
print("iris_data_set_feature_name: \n{}".format(iris_dataset['feature_names']))

iris_data_set_feature_name: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [9]:
#label 이름 확인
print("iris_data_set_target_name: \n{}".format(iris_dataset['target_names']))

iris_data_set_target_name: 
['setosa' 'versicolor' 'virginica']


In [10]:
#데이터 크기 확인
print("iris_data_set_size: \n{}".format(iris_dataset['data'].shape))

iris_data_set_size: 
(150, 4)


In [11]:
#head 5 줄 확인
print("iris_data_set_head5: \n{}".format(iris_dataset['data'][:5]))

iris_data_set_head5: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [12]:
#label 데이터 타입 확인
print("iris_data_set_type \n{}".format(type(iris_dataset['target'])))

iris_data_set_type 
<class 'numpy.ndarray'>
